import type { Plugin } from 'vite'

/**
 * Emits the service worker, with the build's own asset names baked into it.
 *
 * This is a station-basement app: the reason it works offline is not
 * neatness, it is that a paramedic weighing a shift offer at 3am is often
 * somewhere with no signal, and an app that needs the network to show a number
 * it computes locally would be lying about what it is.
 *
 * Hand-written rather than generated, because the whole strategy is fifteen
 * lines and a generated worker is fifteen hundred nobody in this repo would
 * read. `IMPLEMENTATION_PLAN.md` §4.7 asks for a precache manifest; the
 * manifest is the build's asset list, which only the bundler knows — hence a
 * plugin rather than a static file in `public/`.
 */
export function pwa(): Plugin {
  let base = '/'

  return {
    name: 'actas-pwa',
    apply: 'build',

    configResolved(config) {
      base = config.base
    },

    generateBundle(_options, bundle) {
      // Everything the bundler emitted, plus the entry document and the files
      // copied out of public/ that the app needs before it can render.
      const assets = Object.keys(bundle)
        .filter((name) => !name.endsWith('.map'))
        .map((name) => base + name)

      const precache = [
        base,
        ...assets,
        `${base}manifest.webmanifest`,
        `${base}icon-192.png`,
      ]

      // The cache name carries a hash of the precache list, so a deploy that
      // changes any asset lands in a new cache and the old one is deleted on
      // activate. Without that, a stale entry could outlive the deploy that
      // replaced it.
      const version = hash(precache.join('|'))

      this.emitFile({
        type: 'asset',
        fileName: 'sw.js',
        source: serviceWorker(precache, version, base),
      })
    },
  }
}

/** A short, stable hash of the precache list — the cache's version tag. */
function hash(input: string): string {
  let h = 0x811c9dc5
  for (let at = 0; at < input.length; at++) {
    h ^= input.charCodeAt(at)
    h = Math.imul(h, 0x01000193)
  }
  return (h >>> 0).toString(36)
}

function serviceWorker(
  precache: readonly string[],
  version: string,
  base: string,
): string {
  return `/*
 * ACTAS OT Calculator — service worker. Generated by vite-pwa.ts; do not edit.
 *
 * Two strategies, chosen by what the request is for:
 *
 * - Navigations go to the network first and fall back to the cached document.
 *   The app has no API and nothing to be stale about except itself, so this is
 *   what makes a deploy visible the moment there is signal.
 * - Everything else is cache-first, which is safe precisely because Vite
 *   fingerprints the filenames: a changed file is a different URL, so a cached
 *   asset can never be the wrong version of itself.
 *
 * There is deliberately no skipWaiting. Swapping the assets under a session
 * mid-calculation to save one reload is a bad trade for an app someone is
 * reading figures off; the new version takes over on the next load.
 */

const CACHE = 'actas-ot-${version}'
const PRECACHE = ${JSON.stringify(precache, null, 2).replace(/\n/g, '\n')}
const DOCUMENT = '${base}'

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)))
})

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(keys.filter((key) => key !== CACHE).map((key) => caches.delete(key))),
      )
      .then(() => self.clients.claim()),
  )
})

self.addEventListener('fetch', (event) => {
  const request = event.request
  if (request.method !== 'GET') return

  const url = new URL(request.url)
  if (url.origin !== self.location.origin) return

  if (request.mode === 'navigate') {
    event.respondWith(
      fetch(request)
        .then((response) => {
          const copy = response.clone()
          caches.open(CACHE).then((cache) => cache.put(DOCUMENT, copy))
          return response
        })
        .catch(() => caches.match(DOCUMENT).then((cached) => cached || Response.error())),
    )
    return
  }

  event.respondWith(
    caches.match(request).then(
      (cached) =>
        cached ||
        fetch(request).then((response) => {
          // Only same-origin successes are worth keeping: an opaque or errored
          // response cached here would be served back forever.
          if (response.ok && response.type === 'basic') {
            const copy = response.clone()
            caches.open(CACHE).then((cache) => cache.put(request, copy))
          }
          return response
        }),
    ),
  )
})
`
}
